[build]
  # Build frontend
  command = "cd koalaroute && npm install && npm run build"
  publish = "koalaroute/dist"

  # Functions folder
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

  # Environment variables (also set in Netlify dashboard)
  ADMIN_EMAIL = "your_admin_email@example.com"
  ADMIN_PASSWORD = "your_app_password"
  AVIASALES_API_KEY = "your_api_key"
  AVIASALES_MARKER = "your_marker"
  JWT_SECRET = "your_jwt_secret"
  MONGO_URI = "your_mongo_uri"
  OPENAI_API_KEY = "your_openai_key"
