# netlify.toml
[build]
  # Install frontend dependencies and build frontend
  command = "npm install --prefix frontend && npm run build --prefix frontend && npm install --prefix netlify/functions"
  
  # Folder where frontend build output is located
  publish = "frontend/dist"

  # Folder where Netlify functions are located
  functions = "netlify/functions"

# Redirect all /api/* requests to the corresponding serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
