# -------------------------------
# Netlify Build & Functions Config
# -------------------------------

[build]
  # Build frontend first with npm, then backend functions with pnpm
  command = "npm install --prefix frontend && npm run build --prefix frontend && pnpm install --prefix netlify/functions"
  
  # Directory where the built frontend assets are located
  publish = "frontend/dist"

  # Directory for Netlify Functions
  functions = "netlify/functions"

# -------------------------------
# Development Settings (Netlify Dev)
# -------------------------------
[dev]
  functions = "netlify/functions"
  port = 3000
  publish = "frontend/dist"

# -------------------------------
# Redirects / Rewrites
# -------------------------------
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
