[build]
  command = "npm install --prefix koalaroute && npm run build --prefix koalaroute"
  publish = "koalaroute/dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
