[build]
  # Build frontend
  command = "cd client && npm install && npm run build"
  publish = "client/dist"

  # Directory where Netlify functions are located
  functions = "netlify/functions"

# Optional: set Node version for Vite & backend
[build.environment]
  NODE_VERSION = "20"

